-- MySQL Script generated by MySQL Workbench
-- Sat Jan  4 23:53:24 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema eco
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `eco` ;

-- -----------------------------------------------------
-- Schema eco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eco` DEFAULT CHARACTER SET utf8 ;
USE `eco` ;

-- -----------------------------------------------------
-- Table `eco`.`TREATMENTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eco`.`TREATMENTS` ;

CREATE TABLE IF NOT EXISTS `eco`.`TREATMENTS` (
  `ID` INT NOT NULL,
  `TREATMENT` JSON NULL,
  `DESCRIPTION` VARCHAR(100) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eco`.`ALEXA_ORDER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eco`.`ALEXA_ORDER` ;

CREATE TABLE IF NOT EXISTS `eco`.`ALEXA_ORDER` (
  `ID` INT NOT NULL,
  `TREATMENTS_ID` INT NOT NULL,
  `TOKEN` VARCHAR(100) NULL,
  `DATE` TIMESTAMP NULL,
  PRIMARY KEY (`ID`, `TREATMENTS_ID`),
  INDEX `fk_ALEXA_ORDER_TREATMENTS_idx` (`TREATMENTS_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ALEXA_ORDER_TREATMENTS`
    FOREIGN KEY (`TREATMENTS_ID`)
    REFERENCES `eco`.`TREATMENTS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eco`.`TREATMENT_HISTORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eco`.`TREATMENT_HISTORY` ;

CREATE TABLE IF NOT EXISTS `eco`.`TREATMENT_HISTORY` (
  `ID` INT NOT NULL,
  `TREATMENTS_ID` INT NOT NULL,
  `DATE` TIMESTAMP NULL,
  PRIMARY KEY (`ID`, `TREATMENTS_ID`),
  INDEX `fk_TREATMENT_HISTORY_TREATMENTS1_idx` (`TREATMENTS_ID` ASC) VISIBLE,
  CONSTRAINT `fk_TREATMENT_HISTORY_TREATMENTS1`
    FOREIGN KEY (`TREATMENTS_ID`)
    REFERENCES `eco`.`TREATMENTS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eco`.`TEMP_EXT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eco`.`TEMP_EXT` ;

CREATE TABLE IF NOT EXISTS `eco`.`TEMP_EXT` (
  `ID` INT NOT NULL,
  `TEMPERATURE` FLOAT NULL,
  `MEASURE_TIME` TIMESTAMP NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eco`.`LUM_EXT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eco`.`LUM_EXT` ;

CREATE TABLE IF NOT EXISTS `eco`.`LUM_EXT` (
  `ID` INT NOT NULL,
  `LUMINOSITY` FLOAT NULL,
  `MEASURE_TIME` TIMESTAMP NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eco`.`HUM_EXT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eco`.`HUM_EXT` ;

CREATE TABLE IF NOT EXISTS `eco`.`HUM_EXT` (
  `ID` INT NOT NULL,
  `HUMIDITY` FLOAT NULL,
  `MEASURE_TIME` TIMESTAMP NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eco`.`POT_INT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eco`.`POT_INT` ;

CREATE TABLE IF NOT EXISTS `eco`.`POT_INT` (
  `ID` INT NOT NULL,
  `TEMPERATURE` FLOAT NULL,
  `HUMIDITY` FLOAT NULL,
  `MEASURE_TIME` TIMESTAMP NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
